name: Deploy Cloudflare Worker

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Cloudflare Workers CLI
              run: npm install -g wrangler

            - name: Install dependencies
              run: npm install --production

            - name: Build and deploy worker
              env:
                    CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_KEY }}
              run: |
                    wrangler deploy
