name: Deploy Cloudflare Worker

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Cloudflare Workers CLI and tomlq
              run: |
                npm install -g wrangler
                pip install yq


            - name: Install dependencies
              run: npm install --production

            - name: Make the request to determine the subdomain
              id: determine_subdomain
              env: 
                CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_KEY }}
                CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
              run: |
                curl -X GET "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/workers/subdomain" \
                -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" | jq -r '.result.subdomain' | echo result=$(cat) >> $GITHUB_OUTPUT
            
            - name: Parse toml to get worker name
              id: determine_worker_name
              run: |
                tomlq -r .name .\wrangler.toml | echo result=$(cat) >> $GITHUB_OUTPUT

            - name: Build and deploy worker
              env:
                CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_KEY }}
                CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
              run: |
                wrangler deploy
                echo "${{ secrets.TELEGRAM_BOT_TOKEN }}" | wrangler secret put TELEGRAM_BOT_TOKEN
                echo "the subdomain is ${{ steps.determine_subdomain.outputs.result }}.${{ steps.determine_subdomain.outputs.result }}.workers.dev"
