name: Deploy full solution

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  precheck:
    uses: ./.github/workflows/check.yml

  prepare_db:
    uses: ./.github/workflows/prepare_db.yml
    needs: precheck
    with:
      d1_database_name: ${{ needs.precheck.outputs.d1_database_name }}
      d1_database_id: ${{ needs.precheck.outputs.d1_database_id }}

  deploy_pages:
    uses: ./.github/workflows/deploy_pages.yml
    needs: precheck
    with:
      pages_name: ${{ needs.precheck.outputs.worker_name }}
  
  deploy_worker:
    uses: ./.github/workflows/deploy_worker.yml
    needs: [precheck, prepare_db, deploy_pages]
    with:
      d1_database_id: ${{ needs.precheck.outputs.d1_database_id }}
      d1_apparent_database_id: ${{ needs.prepare_db.outputs.d1_apparent_database_id }}
      pages_url: ${{ needs.deploy_pages.outputs.pages_url }}
      worker_url: ${{ needs.precheck.outputs.worker_url }}



    